# Automatically generated by "pub global run bazel:bazelify".
# DO NOT MODIFY BY HAND

# Bazelify: 1 libraries.
load("@io_bazel_rules_dart//dart/build_rules:core.bzl", "dart_library")

package(default_visibility = ["//visibility:public"])

_PUB_DEPS = [
    "@collection//:collection",
]

# Generated automatically for package:pub_semver
dart_library(
    name = "pub_semver",
    srcs = glob(["lib/**"]),
    deps = _PUB_DEPS,
    pub_pkg_name = "pub_semver",
)
