# Automatically generated by "pub global run bazel:bazelify".
# DO NOT MODIFY BY HAND

# Bazelify: 1 libraries.
load("@io_bazel_rules_dart//dart/build_rules:core.bzl", "dart_library")

package(default_visibility = ["//visibility:public"])

_PUB_DEPS = [
    "@analyzer//:analyzer",
    "@args//:args",
    "@async//:async",
    "@barback//:barback",
    "@boolean_selector//:boolean_selector",
    "@collection//:collection",
    "@glob//:glob",
    "@http_multi_server//:http_multi_server",
    "@matcher//:matcher",
    "@package_resolver//:package_resolver",
    "@path//:path",
    "@pool//:pool",
    "@pub_semver//:pub_semver",
    "@shelf//:shelf",
    "@shelf_packages_handler//:shelf_packages_handler",
    "@shelf_static//:shelf_static",
    "@shelf_web_socket//:shelf_web_socket",
    "@source_map_stack_trace//:source_map_stack_trace",
    "@source_maps//:source_maps",
    "@source_span//:source_span",
    "@stack_trace//:stack_trace",
    "@stream_channel//:stream_channel",
    "@string_scanner//:string_scanner",
    "@web_socket_channel//:web_socket_channel",
    "@yaml//:yaml",
]

# Generated automatically for package:test
dart_library(
    name = "test",
    srcs = glob(["lib/**"]),
    deps = _PUB_DEPS,
    pub_pkg_name = "test",
)
